-- Estadísticas (primero, para generar los IDs 1-12)
INSERT INTO estadisticas (unidades_vendidas, devoluciones, rating_promedio) VALUES (150, 5, 4);
INSERT INTO estadisticas (unidades_vendidas, devoluciones, rating_promedio) VALUES (200, 10, 3);
INSERT INTO estadisticas (unidades_vendidas, devoluciones, rating_promedio) VALUES (500, 5, 5);
INSERT INTO estadisticas (unidades_vendidas, devoluciones, rating_promedio) VALUES (300, 15, 4);
INSERT INTO estadisticas (unidades_vendidas, devoluciones, rating_promedio) VALUES (1250, 20, 5);
INSERT INTO estadisticas (unidades_vendidas, devoluciones, rating_promedio) VALUES (100, 10, 4);
INSERT INTO estadisticas (unidades_vendidas, devoluciones, rating_promedio) VALUES (200, 0, 5);
INSERT INTO estadisticas (unidades_vendidas, devoluciones, rating_promedio) VALUES (50, 2, 1);
INSERT INTO estadisticas (unidades_vendidas, devoluciones, rating_promedio) VALUES (75, 5, 3);
INSERT INTO estadisticas (unidades_vendidas, devoluciones, rating_promedio) VALUES (1000, 50, 4);
INSERT INTO estadisticas (unidades_vendidas, devoluciones, rating_promedio) VALUES (400, 20, 5);
INSERT INTO estadisticas (unidades_vendidas, devoluciones, rating_promedio) VALUES (600, 30, 4);

-- Productos (segundo, referenciando estadisticas_id = 1..12 en orden)
INSERT INTO producto (nombre, imagen, descripcion, categoria, precio, descuento, precio_final, cant_jugadores, duracion, stock, dificultad, esta_disponible, creado_at, estadisticas_id) VALUES ('terraforming mars', 'terraforming-mars.jpg', 'Un juego de estrategia donde los jugadores compiten para terraformar Marte y hacerlo habitable.', 'ESTRATEGIA', 65000, 0.15, 55250, '1-5', '90-120 MIN', 12, 5, true, NOW(), 1);
INSERT INTO producto (nombre, imagen, descripcion, categoria, precio, descuento, precio_final, cant_jugadores, duracion, stock, dificultad, esta_disponible, creado_at, estadisticas_id) VALUES ('ajedrez', 'ajedrez.jpg', 'El clásico juego de estrategia donde dos jugadores compiten usando táctica, lógica y planificación.', 'ESTRATEGIA', 25000, 0.20, 20000, '2', 'Ilimitado', 20, 4, true, NOW(), 2);
INSERT INTO producto (nombre, imagen, descripcion, categoria, precio, descuento, precio_final, cant_jugadores, duracion, stock, dificultad, esta_disponible, creado_at, estadisticas_id) VALUES ('catan', 'catan.jpg', 'Un juego de estrategia y comercio donde los jugadores construyen aldeas, caminos y ciudades para dominar la isla.', 'ESTRATEGIA', 50000, 0.10, 45000, '3-4', '60-120 MIN', 30, 3, true, NOW(), 3);
INSERT INTO producto (nombre, imagen, descripcion, categoria, precio, descuento, precio_final, cant_jugadores, duracion, stock, dificultad, esta_disponible, creado_at, estadisticas_id) VALUES ('pandemic', 'pandemic.jpg', 'Un juego cooperativo donde los jugadores trabajan juntos para detener enfermedades y salvar al mundo.', 'COOPERATIVO', 48000, 0.10, 43200, '2-4', '45-60 MIN', 25, 4, true, NOW(), 4);
INSERT INTO producto (nombre, imagen, descripcion, categoria, precio, descuento, precio_final, cant_jugadores, duracion, stock, dificultad, esta_disponible, creado_at, estadisticas_id) VALUES ('the crew', 'the_crew.png', 'Un juego cooperativo de cartas donde los jugadores completan misiones espaciales usando estrategia y comunicación.', 'COOPERATIVO', 22000, 0.15, 18700, '2-5', '20-60 MIN', 40, 3, true, NOW(), 5);
INSERT INTO producto (nombre, imagen, descripcion, categoria, precio, descuento, precio_final, cant_jugadores, duracion, stock, dificultad, esta_disponible, creado_at, estadisticas_id) VALUES ('arkham horror', 'arkham_horror.jpg', 'Un juego cooperativo de terror e investigación inspirado en el universo de Lovecraft.', 'COOPERATIVO', 70000, 0.20, 56000, '1-8', '120+ MIN', 15, 5, true, NOW(), 6);
INSERT INTO producto (nombre, imagen, descripcion, categoria, precio, descuento, precio_final, cant_jugadores, duracion, stock, dificultad, esta_disponible, creado_at, estadisticas_id) VALUES ('dungeon and dragons', 'dungeons_dragons.jpg', 'Un juego de rol de fantasía donde los jugadores crean personajes, viven aventuras y exploran mundos mágicos.', 'ROL', 60000, 0.15, 51000, '3-6', '120+ MIN', 30, 5, true, NOW(), 7);
INSERT INTO producto (nombre, imagen, descripcion, categoria, precio, descuento, precio_final, cant_jugadores, duracion, stock, dificultad, esta_disponible, creado_at, estadisticas_id) VALUES ('call of cthulhu', 'cthulhu.jpg', 'Un juego de rol de horror e investigación inspirado en las historias de H.P. Lovecraft.', 'ROL', 55000, 0.10, 49500, '1-6', '60-180 MIN', 10, 5, true, NOW(), 8);
INSERT INTO producto (nombre, imagen, descripcion, categoria, precio, descuento, precio_final, cant_jugadores, duracion, stock, dificultad, esta_disponible, creado_at, estadisticas_id) VALUES ('vampire: the masquerade', 'vampire_rivals.jpg', 'Un juego de rol narrativo donde los jugadores interpretan vampiros en un mundo oscuro y lleno de secretos.', 'ROL', 45000, 0.10, 40500, '3-4', '60-120 MIN', 7, 4, true, NOW(), 9);
INSERT INTO producto (nombre, imagen, descripcion, categoria, precio, descuento, precio_final, cant_jugadores, duracion, stock, dificultad, esta_disponible, creado_at, estadisticas_id) VALUES ('uno no mercy', 'uno.png', 'Un juego de cartas rápido y divertido donde los jugadores compiten para quedarse sin cartas antes que los demás.', 'CASUAL', 8000, 0.0, 8000, '2-10', '15-30 MIN', 3, 1, true, NOW(), 10);
INSERT INTO producto (nombre, imagen, descripcion, categoria, precio, descuento, precio_final, cant_jugadores, duracion, stock, dificultad, esta_disponible, creado_at, estadisticas_id) VALUES ('dixit', 'dixit.jpg', 'Un juego casual de imaginación y creatividad donde las cartas cuentan historias mediante ilustraciones artísticas.', 'CASUAL', 30000, 0.05, 28500, '3-6', '15-45 MIN', 5, 2, true, NOW(), 11);
INSERT INTO producto (nombre, imagen, descripcion, categoria, precio, descuento, precio_final, cant_jugadores, duracion, stock, dificultad, esta_disponible, creado_at, estadisticas_id) VALUES ('exploding kittens', 'exploding_kittens.jpg', 'Un juego de cartas caótico y humorístico donde los jugadores intentan evitar explotar mientras sabotean a sus rivales.', 'CASUAL', 18000, 0.10, 16200, '2-5', '15-30 MIN', 8, 2, true, NOW(), 12);