services:

  mysql:
    image: mysql:8.0
    container_name: mysql-jumanji
    environment:
      MYSQL_DATABASE: jumanji_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    image: ms-jumanji-backend
    container_name: backend-jumanji
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy